# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: local_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init:/docker-entrypoint-initdb.d/
